name: couple_wallet
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  get: any
  firebase_core: any

  # Services
  ## Cloud firestore to store data
  cloud_firestore: ^5.0.1
  ## Notification
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2
  googleapis_auth: ^1.6.0
  ## Crashlytics
  firebase_crashlytics: ^4.0.1

  # Resources
  flutter_gen: ^5.4.0
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.3.0

  # Utils
  intl: ^0.18.1
  intl_utils: ^2.8.5
  logger: ^2.2.0
  connectivity_plus: ^5.0.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  share_plus: 9.0.0
  uuid: ^4.4.0
  package_info_plus: ^8.0.0

  # UI Components
  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.1.0
  animations: ^2.0.11
  shimmer: ^3.0.0
  lottie: ^3.1.0
  google_nav_bar: ^5.0.6
  gap: any
  font_awesome_flutter: ^10.7.0

  # Data
  shared_preferences: ^2.2.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons:
    git:
      url: https://github.com/lux-studio-66/flutter_launcher_icons.git
      ref: 591cb24

flutter_gen:
  output: lib/resources/generated/assets

  integrations:
    flutter_svg: true
    lottie: true

  fonts:
    enabled: true

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: vi
  output_dir: lib/resources/generated/strings
  arb_dir: lib/resources/strings

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/pngs/app_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/json/
    - serviceAccountKey.json